<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('Areas', 'ppit-equipment', $context->getLocale()) ?></strong>
            </div>
		    <div class="panel-body">

		    	<div class="row">

<!-- Filter on caption -->
				    <div class="col-md-4 col-md-offset-4">
						<div class="form-group has-feedback">
							<input type="text" class="form-control" id="caption_search" />
							<span class="glyphicon glyphicon-search form-control-feedback"></span>
						</div>
					</div>

				</div>

<!-- Add or update section -->
				<div id="area_list"></div>
				
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id="area_index_script">

// List section
function getAreaList(param, input) {
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			document.getElementById('area_list').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('getAreaList, route = ' + '<?php echo $this->url('area/list') ?>?' + param + '=' + input);
			console.log(xhttp.responseText);
<?php endif;?>
			eval(document.getElementById('area_list_script').innerHTML);
		}
	}
	xhttp.open('GET', '<?php echo $this->url('area/list') ?>?' + param + '=' + input, true);
	xhttp.send();
}

$('#caption_search').keyup(function () {
	var input = document.getElementById('caption_search').value;
	if (input == '' || input.length >= 2) {
		getAreaList('caption_search', input);
	}
	else {
		document.getElementById('area_list').innerHTML = '';
	}
});
$('#caption_search').focus();

getAreaList('caption_search', '');

</script>
