<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$isDeletable = $area->isDeletable();
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('Area: update', 'ppit-equipment', $context->getLocale()) ?></strong>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td>

<!-- Detail -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Equipments', 'ppit-equipment', $context->getLocale()),
									'id' => 'detail-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
							)) ?>
						
<?php if ($id) : ?>
<!-- Delete -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor',
									'anchorStyle' => $anchorStyle,
									'class' => ($isDeletable) ? 'btn-danger' : 'btn-disabled',
									'disabled' => !$isDeletable,
									'spa' => $spa,
							)) ?>
<?php endif;?>
						</td>
					</tr>

				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'id' => $id,
			'update_time' => $area->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('area/update')) $isDisabled = true; else $isDisabled = false; ?>

<!-- Organizational unit -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'org_unit_identifier',
		'label' => $this->translate('Site', 'ppit-equipment', $context->getLocale()),
		'value' => $area->org_unit_identifier,
		'isMandatory' => false,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
<input type="hidden" id="org_unit_id" name="org_unit_id" value="<?php echo $area->org_unit_id ?>" />

<!-- Caption -->

	<?php
		echo $this->partial('/partials/input-widget.phtml', array(
			'property' => 'caption',
			'label' => $this->translate('Caption', 'ppit-core', $context->getLocale()),
			'value' => $area->caption,
			'isMandatory' => true,
			'maxLength' => 255,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>
	
<?php foreach ($area->availableProperties as $property => $params) : ?>

<!-- <?php echo $property ?> -->

<?php if ($params['type'] == 'input') : ?>
	<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'isMandatory' => false,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>

<?php elseif ($params['type'] == 'number') : ?>
	<?php echo $this->partial('/partials/number-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'isMandatory' => false,
		'min' => $params['min'],
		'max' => $params['max'],
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>

<?php elseif ($params['type'] == 'date') : ?>
	<?php echo $this->partial('/partials/date-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'isMandatory' => false,
		'minDate' => $params['minDate'],
		'maxDate' => $params['maxDate'],
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>

<?php elseif ($params['type'] == 'textarea') : ?>
	<?php echo $this->partial('/partials/textarea-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'rows' => 3, 
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'isMandatory' => false,
		'maxLength' => $params['maxLength'],
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>
					
<?php elseif ($params['type'] == 'select') : ?>
	<?php
	$modalities = array();
	foreach ($params['modalities'] as $modality) $modalities[$modality] = $modality;
	echo $this->partial('/partials/select-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'modalities' => $modalities,
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'isMandatory' => false,
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>

<?php elseif ($params['type'] == 'checkbox') : ?>
	<?php
	echo $this->partial('/partials/checkbox-widget.phtml', array(
		'property' => $property,
		'label' => $this->translate($params['label'], 'ppit-equipment', $context->getLocale()),
		'value' => (array_key_exists($property, $area->properties)) ? $area->properties[$property] : null,
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>

<?php endif;?>

<?php endforeach;?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer') ?>

			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<?php if (!$context->isSpaMode()) echo $this->partial('partials/view-controller') ?>

<script id='area_update_script'>

$('#org_unit_identifier').autocomplete({
	source : function(request, response){
    $.ajax({
    		url : '<?php echo $this->url('orgUnit/dataList') ?>', // Server request returning json data
            dataType : 'json', // The data type is json
            data : {
                name : $('#org_unit_identifier').val(), // Giving the prefix (at least 3 chars input)
                maxRows : 15
            },
            
            success : function(donnee){
	            response($.map(donnee.data, function(object){
	        		document.getElementById("org_unit_id").value = object.id;
		            return object.identifier + ' - ' + object.caption;
        	    }));
            }
        });
    }
});
	
// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('area/index'),
		'spa' => $spa,
)) ?>

// Detail
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'detail-anchor',
		'route' => $this->url('area/detail', array('id' => $id)),
		'script' =>'area_detail_script',
		'spa' => $spa,
)) ?>

<?php if ($id) : ?>
// Delete
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'delete-anchor',
		'route' => $this->url('area/delete', array('id' => $id)),
		'script' =>'area_delete_script',
		'spa' => $spa,
)) ?>
<?php endif;?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('area/index'),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('area/index'),
		'spa' => $spa,
)) ?>

// Submit
<?php
$properties = array('org_unit_identifier' => 'input', 'org_unit_id' => 'hidden', 'caption' => 'input', 'update_time' => 'hidden');
foreach ($area->availableProperties as $property => $params) $properties[$property] = $params['type'];
echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'formRoute' => $this->url('area/update', array('id' => $id)),
		'formScript' => 'area_update_script',
		'properties' => $properties,
		'mainRoute' => $this->url('area/index'),
		'mainScript' =>'area_index_script',
		'hideForm' => false,
)) ?>

<?php endif;?>

</script>
