<?php
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'formId' => 'equipment-lock-form',
			'update_time' => $equipment->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('equipment/lock')) $isDisabled = true; else $isDisabled = false; ?>

<?php if ($type == 'move') : ?>

	<!-- Target Area -->
	<?php
		echo $this->partial('/partials/input-widget.phtml', array(
			'property' => 'target_area_caption',
			'label' => $this->translate('Target area', 'ppit-equipment', $context->getLocale()),
			'value' => $equipment->target_area_caption,
			'isMandatory' => false,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>
	<input type="hidden" id="target_area_id" name="target_area_id" />

<?php elseif ($type == 'change') : ?>

<!-- Target Product -->

	<?php
		echo $this->partial('/partials/input-widget.phtml', array(
			'property' => 'target_product_caption',
			'label' => $this->translate('Target model', 'ppit-equipment', $context->getLocale()),
			'value' => $equipment->target_product_caption,
			'isMandatory' => true,
			'maxLength' => 255,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>

<?php endif;?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'prefix' => 'equipment_',
	'message' => $message,
	'context' => $context,
)) ?>

<hr>

<script id='equipment_lock_script'>

<?php $properties = array('update_time' => 'hidden'); ?>

<?php if ($type == 'move') : ?>
	<?php
	$properties['target_area_identifier'] = 'input';
	$properties['target_area_id'] = 'hidden';
	?>
	
	$('#target_area_caption').autocomplete({
		source : function(request, response){
	    $.ajax({
	    		url : '<?php echo $this->url('area/dataList') ?>', // Server request returning json data
	            dataType : 'json', // The data type is json
	            data : {
	                caption : $('#target_area_caption').val(), // Giving the prefix (at least 3 chars input)
	                maxRows : 15
	            },
	            
	            success : function(donnee){
		            response($.map(donnee.data, function(object){
		        		document.getElementById("target_area_id").value = object.id;
			            return object.caption;
	        	    }));
	            }
	        });
	    }
	});

<?php elseif ($type == 'change') : ?>
	<?php
	$properties['target_product_caption'] = 'input';
	$properties['target_product_id'] = 'hidden';
	?>
	
	$('#target_product_caption').autocomplete({
		source : function(request, response){
	    $.ajax({
	    		url : '<?php echo $this->url('product/dataList', array('product_category_id' => $equipment->product_category_id)) ?>',
	            dataType : 'json', // The data type is json
	            data : {
	                caption : $('#target_product_caption').val(), // Giving the prefix (at least 3 chars input)
	                maxRows : 15
	            },
	            
	            success : function(donnee){
		            response($.map(donnee.data, function(object){
		        		document.getElementById("target_product_id").value = object.id;
			            return object.caption;
	        	    }));
	            }
	        });
	    }
	});

<?php endif;?>

<?php if ($message == 'OK') : ?>

	$('#equipment-return-anchor').click(function () {
		reload(
			'<?php echo $this->url('equipment/list', array('area_id' => $equipment->area_id)) ?>',
			'equipment_list_script',
			'equipment_list'
		);
	} );

<?php else : ?>

	$('#equipment_cancel-anchor').click(function () {
		reload(
			'<?php echo $this->url('equipment/list', array('area_id' => $equipment->area_id)) ?>',
			'equipment_list_script',
			'equipment_list'
		);
	} );

	// Submit
	<?php
	echo $this->partial('/partials/form-button-script', array(
			'context' => $context,
			'formId' => 'equipment-lock-form',
			'id' => 'submit-button',
			'checkFunction' => 'checkForm',
			'formRoute' => $this->url('equipment/lock', array('type' => $type, 'id' => $id)),
			'formScript' => 'equipment_lock_script',
			'target' => 'equipment_list',
			'properties' => $properties,
			'mainRoute' => null,
			'hideForm' => false,
	)) ?>
	
	function checkForm() {
		validity = true;
		if (document.getElementById('target_area_id').value == '') {
			validity = false;
			renderElement('target_area_caption', '<?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?>')
		}
		if (document.getElementById('target_product_id').value == '') {
			validity = false;
			renderElement('target_product_caption', '<?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?>')
		}
		return validity;
	}

<?php endif;?>

</script>
