<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<div class="panel panel-default">
    <div class="panel-heading">
		<strong><?php echo $this->translate('What-if', 'ppit-equipment', $context->getLocale())?>: <?php echo ($id) ? $equipment->product_brand.' - '.$equipment->product_caption : $this->translate('Add', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<?php echo $this->partial('/partials/anchor-widget.phtml', array(
				'glyphicon' => 'glyphicon-remove',
				'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
				'id' => 'remove-anchor',
				'anchorStyle' => $anchorStyle,
				'spa' => $spa,
			)) ?>
 		</div>
	</div>
	
<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'id' => $id,
			'update_time' => $equipment->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('equipment/lock')) $isDisabled = true; else $isDisabled = false; ?>

<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Options', 'ppit-master-data', $context->getLocale())?></label>
</div>

<div id="options">
<?php foreach ($equipment->availableOptions as $option) : ?>

	<!-- Option -->
	<?php
	echo $this->partial('/partials/checkbox-widget.phtml', array(
		'property' => 'option_'.$option->id,
		'label' => $option->caption.' - '.$option->description.' ('.number_format($option->prices[$area->place->tax_regime],2,',',' ').' €'.')',
		'value' => null,
		'context' => $context,
		'isDisabled' => $isDisabled,
	)); ?>
<?php endforeach; ?>
</div>

<hr>

<!-- What-if action -->
<input type="hidden" id="what_if_action" name="what_if_action" />

<!-- Move -->
<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Move', 'ppit-equipment', $context->getLocale()) ?></label>
	<div class="col-sm-7">
		<input type="radio" name="move_radio" id="move_radio" /> 
	</div>
</div>

<!-- Target Area -->
<?php
	$properties = array();
	foreach ($equipment->availableAreas as $area) $properties[$area->id] = $area->site_caption.' - '.$area->caption;
	echo $this->partial('/partials/select-widget.phtml', array(
		'property' => 'target_area_id',
		'label' => $this->translate('Target area', 'ppit-equipment', $context->getLocale()),
		'modalities' => $properties,
		'value' => $equipment->target_area_id,
		'isMandatory' => true,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Change -->
<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Exchange', 'ppit-equipment', $context->getLocale()) ?></label>
	<div class="col-sm-7">
		<input type="radio" name="change_radio" id="change_radio" /> 
	</div>
</div>

<!-- Target Product -->

<?php
	$properties = array();
	foreach ($equipment->availableProducts as $product) $properties[$product->id] = $product->brand.' - '.$product->caption;
	echo $this->partial('/partials/select-widget.phtml', array(
		'property' => 'target_product_id',
		'label' => $this->translate('Target model', 'ppit-equipment', $context->getLocale()),
		'modalities' => $properties,
		'value' => $equipment->target_product_id,
		'isMandatory' => true,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Delete -->
<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Withdraw', 'ppit-equipment', $context->getLocale()) ?></label>
	<div class="col-sm-7">
		<input type="radio" name="delete_radio" id="delete_radio" /> 
	</div>
</div>

<!-- Reset -->
<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Reset', 'ppit-equipment', $context->getLocale()) ?></label>
	<div class="col-sm-7">
		<input type="radio" name="reset_radio" id="reset_radio" /> 
	</div>
</div>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer') ?>

</div>

<script id='equipment/update-script'>

<?php $properties = array('what_if_action' => 'hidden', 'target_area_id' => 'select', 'target_product_id' => 'select', 'update_time' => 'hidden'); ?>

$("#move_radio").click(function () { checkMove(); } );
$("#target_area_id").change(function () { checkMove(); } );
$("#change_radio").click(function () { checkChange(); } );
$("#target_product_id").change(function () { checkChange(); } );
$("#delete_radio").click(function () { checkDelete(); } );
$("#reset_radio").click(function () { checkReset(); } );

function checkMove() {
	document.getElementById('what_if_action').value = 'move';
	document.getElementById('move_radio').checked='checked';
	document.getElementById('change_radio').checked='';
	document.getElementById('delete_radio').checked='';
	document.getElementById('reset_radio').checked='';
}

function checkChange() {
	document.getElementById('what_if_action').value = 'change';
	document.getElementById('move_radio').checked='';
	document.getElementById('change_radio').checked='checked';
	document.getElementById('delete_radio').checked='';
	document.getElementById('reset_radio').checked='';
}

function checkDelete() {
	document.getElementById('what_if_action').value = 'delete';
	document.getElementById('move_radio').checked='';
	document.getElementById('change_radio').checked='';
	document.getElementById('delete_radio').checked='checked';
	document.getElementById('reset_radio').checked='';
}

function checkReset() {
	document.getElementById('what_if_action').value = 'reset';
	document.getElementById('move_radio').checked='';
	document.getElementById('change_radio').checked='';
	document.getElementById('delete_radio').checked='';
	document.getElementById('reset_radio').checked='checked';
}

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('area/index'),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('area/index'),
		'spa' => $spa,
)) ?>

// Submit
<?php
echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'checkFunction' => 'checkForm',
		'formRoute' => $this->url('equipment/update', array('area_id' => $area_id, 'product_category_id' => $product_category_id, 'id' => $id)),
		'formScript' => 'equipment/update-script',
		'target' => 'equipment-update',
		'properties' => $properties,
		'mainRoute' => null,
		'hideForm' => false,
)) ?>

function checkForm() {
	validity = true;
	if (document.getElementById('what_if_action').value == 'move') {
		if (document.getElementById('target_area_id').value == '') validity = false;
	}
	else if (document.getElementById('what_if_action').value == 'change') {
		if (document.getElementById('target_product_id').value == '') validity = false;
	}
	return validity;
}

<?php endif;?>

</script>
